// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveTask(arg1) {
  return window['go']['main']['App']['ArchiveTask'](arg1);
}

export function CreateTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3, arg4);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetAllTasks() {
  return window['go']['main']['App']['GetAllTasks']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetArchivedTasks() {
  return window['go']['main']['App']['GetArchivedTasks']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetTaskByID(arg1) {
  return window['go']['main']['App']['GetTaskByID'](arg1);
}

export function GetTasksByPriority(arg1) {
  return window['go']['main']['App']['GetTasksByPriority'](arg1);
}

export function GetTasksByStatus(arg1) {
  return window['go']['main']['App']['GetTasksByStatus'](arg1);
}

export function GetTasksStats() {
  return window['go']['main']['App']['GetTasksStats']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HealthCheck() {
  return window['go']['main']['App']['HealthCheck']();
}

export function ToggleTaskStatus(arg1) {
  return window['go']['main']['App']['ToggleTaskStatus'](arg1);
}

export function UpdateTask(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2, arg3, arg4, arg5);
}
