// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ArchiveTask(arg1:number):Promise<models.Task>;

export function CreateTask(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.Task>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetAllTasks():Promise<Array<models.Task>>;

export function GetAppInfo():Promise<Record<string, any>>;

export function GetArchivedTasks():Promise<Array<models.Task>>;

export function GetDashboardStats():Promise<any>;

export function GetTaskByID(arg1:number):Promise<models.Task>;

export function GetTasksByPriority(arg1:string):Promise<Array<models.Task>>;

export function GetTasksByStatus(arg1:string):Promise<Array<models.Task>>;

export function GetTasksStats():Promise<any>;

export function Greet(arg1:string):Promise<string>;

export function HealthCheck():Promise<Record<string, any>>;

export function ToggleTaskStatus(arg1:number):Promise<models.Task>;

export function UpdateTask(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<models.Task>;
